import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../core/app_branding.dart';
import '../models/purchase.dart';
import '../models/sale.dart';
import '../utils/formatters.dart';

class PdfInvoiceService {
  Future<Uint8List> buildPurchaseInvoice(Purchase purchase) async {
    final doc = pw.Document();
    doc.addPage(
      _buildInvoicePage(
        title: 'Purchase Invoice',
        invoiceNumber: purchase.invoiceNumber,
        partyLabel: 'Seller',
        partyName: purchase.sellerName,
        date: purchase.createdAt,
        rows: purchase.items
            .map(
              (item) => [
                item.materialName,
                Formatters.kg(item.weightKg),
                Formatters.money(item.rate),
                Formatters.money(item.amount),
              ],
            )
            .toList(),
        total: purchase.totalAmount,
        paid: purchase.paidAmount,
        balance: purchase.balanceAmount,
      ),
    );
    return doc.save();
  }

  Future<Uint8List> buildSalesInvoice(Sale sale) async {
    final doc = pw.Document();
    final qrImage = await _loadPaymentQrImage();
    doc.addPage(
      _buildInvoicePage(
        title: 'Sales Invoice',
        invoiceNumber: sale.invoiceNumber,
        partyLabel: 'Customer',
        partyName: sale.customerName,
        date: sale.createdAt,
        rows: sale.items
            .map(
              (item) => [
                item.materialName,
                Formatters.kg(item.weightKg),
                Formatters.money(item.rate),
                Formatters.money(item.amount),
              ],
            )
            .toList(),
        total: sale.totalAmount,
        paid: sale.receivedAmount,
        balance: sale.balanceAmount,
        includePaymentDetails: true,
        qrImage: qrImage,
      ),
    );
    return doc.save();
  }

  pw.Page _buildInvoicePage({
    required String title,
    required String invoiceNumber,
    required String partyLabel,
    required String partyName,
    required DateTime date,
    required List<List<String>> rows,
    required double total,
    required double paid,
    required double balance,
    bool includePaymentDetails = false,
    pw.MemoryImage? qrImage,
  }) {
    return pw.Page(
      pageTheme: const pw.PageTheme(
        margin: pw.EdgeInsets.all(32),
        pageFormat: PdfPageFormat.a4,
      ),
      build: (context) {
        return pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              appDisplayName,
              style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 4),
            pw.Text('Complete Smart Scrap Management'),
            pw.Divider(height: 28),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(title, style: pw.TextStyle(fontSize: 18)),
                pw.Text(invoiceNumber),
              ],
            ),
            pw.SizedBox(height: 16),
            pw.Text('$partyLabel: $partyName'),
            pw.Text('Date: ${Formatters.dateTime(date)}'),
            pw.SizedBox(height: 24),
            pw.TableHelper.fromTextArray(
              headers: const ['Item', 'Weight', 'Rate', 'Amount'],
              data: rows,
              headerDecoration: const pw.BoxDecoration(color: PdfColors.blue50),
              border: pw.TableBorder.all(color: PdfColors.grey300),
            ),
            pw.SizedBox(height: 18),
            _totalRow('Total', total),
            _totalRow('Paid / Received', paid),
            _totalRow('Balance', balance, bold: true),
            if (includePaymentDetails) ...[
              pw.SizedBox(height: 18),
              _sectionTitle('PAYMENT DETAILS'),
              _paymentDetails(qrImage),
            ],
            pw.Spacer(),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Generated by Scrap Management System'),
                pw.Text('Authorised Signature'),
              ],
            ),
          ],
        );
      },
    );
  }

  pw.Widget _sectionTitle(String value) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
      color: PdfColors.blueGrey800,
      child: pw.Text(
        value,
        style: pw.TextStyle(
          color: PdfColors.white,
          fontWeight: pw.FontWeight.bold,
        ),
      ),
    );
  }

  pw.Widget _paymentDetails(pw.MemoryImage? qrImage) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey500, width: 0.5),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Bank Name        : $paymentBankName'),
                pw.Text('Account Name     : $paymentAccountName'),
                pw.Text('Account Number   : $paymentAccountNumber'),
                pw.Text('GPay / UPI No    : $paymentUpiMobile'),
                pw.Text('G-Pay Number-$paymentGPayNumber'),
              ],
            ),
          ),
          pw.SizedBox(width: 16),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              if (qrImage == null)
                pw.Container(
                  width: 96,
                  height: 96,
                  alignment: pw.Alignment.center,
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey500),
                  ),
                  child: pw.Text(
                    paymentUpiMobile,
                    textAlign: pw.TextAlign.center,
                    style: const pw.TextStyle(fontSize: 8),
                  ),
                )
              else
                pw.Image(
                  qrImage,
                  width: 96,
                  height: 96,
                  fit: pw.BoxFit.contain,
                ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Scan to Pay with any UPI App',
                textAlign: pw.TextAlign.center,
                style: pw.TextStyle(
                  fontSize: 8,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Future<pw.MemoryImage?> _loadPaymentQrImage() async {
    try {
      final data = await rootBundle.load(paymentQrAssetPath);
      return pw.MemoryImage(data.buffer.asUint8List());
    } catch (_) {
      return null;
    }
  }

  pw.Widget _totalRow(String label, double value, {bool bold = false}) {
    final style = bold ? pw.TextStyle(fontWeight: pw.FontWeight.bold) : null;
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 6),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.end,
        children: [
          pw.Text('$label: ', style: style),
          pw.SizedBox(width: 8),
          pw.Text(Formatters.money(value), style: style),
        ],
      ),
    );
  }
}
